### ISSUE TITLE
Publish to Clojars, perhaps?

### ISSUE THREAD

**Issue by acron0** [maxnoel/clj-lolapi#2]
Hiya, I'd love to use this and if it were published to Clojars then the experience would be even more frictionless ;) Whaddya say?

**Comment by maxnoel** [comment]
Sure. I haven't had the time to work on this at all recently, and I'm gonna be busy until the end of the week (I'm attending PyCon), but I'll double-check that everything's still working and make a Clojars release afterwards.

**Comment by acron0** [comment]
https://clojars.org/clj-lolapi
